- pull-request-template.md
This PR will add a PR template as well as test our new permissions for PRs.
> Add pr template

- .travis.yml
- alembic.ini
- alembic/README
- alembic/env.py
- alembic/script.py.mako
- alembic/versions/8c089a511ab7_create_plants.py
This PR will create BE migrations and set up the DB.  **It does not have any additional tests yet!
This change will allow the input of plants into the DB.
Nope
We created migrations using alembic.
> Migrations

- Procfile
- alembic/versions/dc382319dd84_seed_db.py
Added a Procfile to root to hopefully get Heroku working
It will hopefully get Heroku working
Nope
Added Procfile to root
> Heroku setup

- .travis.yml
- alembic/versions/752c338c6328_seed_db.py
- alembic/versions/8c089a511ab7_create_plants.py
Finished the bulk insert with seed data. Had to redo migrations in order for it to run successfully.
This change was made to ensure that there was data in our database for testing and production
Yes, replaced the migration files with new migrations to avoid version number issues and revision number misalignment
We also added a line to the travis configuration to ensure that the migrations were run before the test
> Bulk Insert

- Procfile
Updated the procfile with a different app name
> Update Procfile Again

- app/__init__.py
Set up SQLAlchemy DB in app configuration
> Add to App Configuration 

- README.md
- app/__init__.py
- app/api/routes.py
- app/models.py
- instance/config.py
- run.py
- tests/test_endpoint.py
Adds a search endpoint to production
This will allow FE to search for plants in our DB
Nope, just new stuff
Added test for endpoint and route for endpoint
> Mh search endpoint

- README.md
- alembic/versions/1d773bfaf33d_add_harvest_date_to_gardens.py
- alembic/versions/8d80e867d3dd_reseed_db.py
- alembic/versions/b557abac858b_update_plants_table.py
- app/api/routes.py
- app/models.py
- tests/test_endpoint.py
- tests/test_models.py
- Plants table
- Removed `name` column
- Changed `annual` column datatype to be a `String` rather than a `Boolean`
- Gardens table
- Add `date_to_harvest` column with `DateTime` datatype
Yes, tests and models were edited to reflect new database tables
> Database Updates

- app/api/routes.py
- tests/test_endpoint.py
- Fix harvest date setting for plants with no harvest
- This change was required to fix an error when hitting the endpoint with a plant who did not have a harvest date
Yes, a conditional was added for creating the harvest date and a test was edited to test the datetime functionality
> Fix Harvest Date

- README.md
- app/api/routes.py
- app/models.py
- Created a complete README
- Added get_all method to plant model that was accidentally removed during a merge conflict
- To update README and add `get_all` so that the "view all plants" endpoint works
No previously written code was changed
> Update README & Fix Merge Error

- README.md
- alembic/versions/165f21d7f610_create_new_garden_table.py
- alembic/versions/45d3bf115dcd_rename_garden_table.py
- alembic/versions/6465b8352ec5_seed_garden.py
- alembic/versions/7ea9effabd2f_add_garden_id_to_joins_table.py
- app/api/routes.py
- app/models.py
- tests/test_endpoint.py
- tests/test_models.py
- Create garden endpoint
- This endpoint returns all plants in your garden
- This was created to serve as a new piece of functionality
No
> Garden Endpoint

- app/api/routes.py
- tests/test_endpoint.py
- Added POST endpoint to update when last watered and testing
- Adds functionality for watering for the FE
No
> Water Information Endpoint

- README.md
- app/api/routes.py
- tests/test_endpoint.py
This adds an endpoint to return a plant's personal information after it has been added to the garden
It will allow the final piece of functionality for our FE to display to satisfy the project's MVP!
Nope, just added!
tests/test_endpoint.py
app/api/routes.py
> Garden plant profile

- README.md
- app/api/routes.py
- tests/test_endpoint.py
Added a few updates requested by the FE:
- A delete endpoint to remove plants from the garden
- Added a days till harvest field in the plant show
- Return a sad path for no plant found in plant search
Adds functionality that will make the app more user friendly
Nope
> Fe requests

- README.md
- app/api/routes.py
- tests/test_endpoint.py
Change a variety of endpoint returns to meet needs of the FE.
Remove Null Values and replace them with 'N/A' return for FE.
Change the water endpoint to PUT instead of POST
Format dates to be the same across the board.
It solves a variety of issues for the FE as well as standardizes returns for our API.
Multiple routes were changed and tests were changed accordingly.
> More fe requests

- app/api/routes.py
- Fixed sad path issue where plant profile could not be rendered if it did not have a harvest date
- Bugfix - To allow our FE team to render a plants profile page
Yes, two lines were moved into a conditional
> Harvest Date Bug

- .gitignore
- tests/test_endpoint.py
- Added more robust testing to all endpoint tests. Added tp ensure fields were coming back as expected and all fields are accounted for.
- This change will allow us to feel confident our code is working as expected and will allow us to easily refactor
All endpoint tests were modified to test the fields specifically
> Robust Testing - Endpoints

- .coveragerc
- .gitignore
- app/models.py
- requirements.txt
- tests/test_endpoint.py
- tests/test_models.py
- Set up coverage and added it to requirements.txt
- Add tests and remove unnecessary code to ensure everything is being tested
- To make sure our code is working as expected
- Kind of, we removed the last two lines of code in each test file and added new tests
> Configure Coverage & Boost Coverage Percentage

- app/api/routes.py
- app/models.py
- tests/test_endpoint.py
- tests/test_models.py
Added model tests
Abstracted DB queries into model and out of routes
Formatted all dates in model methods (which seems to have solved the problems with DateTimes not being accurate)
This brought us from 95% test coverage to 100%!
Just refactored
> Model methods

- app/api/routes.py
- tests/test_endpoint.py
- tests/test_models.py
- Reorganize code to be sorted by model
- This was done to help anyone reading the code understand whats happening
- It was moved around
> Reorganize Code

- app/api/routes.py
- app/models.py
- tests/test_endpoint.py
- tests/test_models.py
-Plant search now returns results alphabetically
-Random plant endpoint pulls random plant from DB, not generating a random ID.  This fixes an issue where an ID could be created for a plant that had been removed form the DB and would potentially cause the system to break.
Removed plant model method of generate random ID and replaced it with get random plant.  Also added an order by line to the plant search method.
> Model method improvements

- README.md
> Update with badges

- README.md
- Add about section and database diagram
> Add about section and DB layout

- app/api/routes.py
One of our time calculations was off and this branch fixes it.  Days till next water is now calculated from last watered, not today.
Time calculations were not working right.
Yes!  The routes for calculating datetimes were changed!
> Fix days till next water calculation

- README.md
Added FE team's githubs to the readme
> Add FE Team's Github profiles

- README.md
Realized this Readme had all good info, but didn't have a link to the actual application in use!  Added one of those and also fixed a typo.
This fix will make it easier for others to see what our work looked like in the end!
Just the typo fixed and a link to the production video added.
> Add production video link to Readme
